# 面试题

## 在 except 中 return 后还会不会执行 finally 中的代码？怎么抛出自定义异常？

会继续处理 finally 中的代码

用 raise 方法可以抛出自定义异常。

## 介绍一下 except 的作用和用法

